### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by danielsz** [nicholasbs/clojurescript-rails#1]
Hi, 

This looks and sounds great. 
I'm utterly confused, though. 

The Clementine gem: ClojureScript on Rails Asset Pipeline
Your README says "heavily inspired by Clementine".

Can you please explain the differences, what you found lacking with the Clementine gem, motivation, etc. 

Just trying to understand. 

Thanks!

**Comment by zachallaun** [comment]
Hi there!

Nick and I started working on this because we were having trouble understanding the Clementine gem. At that time, Clementine only supported JRuby (I believe this has since changed) and we wanted to be able to use CLJS from Ruby MRI. (We never really finished the job, so please don't expect any of this to work!)

Since then, I believe Clementine has been updated to support Ruby MRI, so if you're interested in pairing Ruby and CLJS, I'd definitely check it out!

Cheers!

**Comment by danielsz** [comment]
Thank you for the explanation, Zach. Happens all the time :-)
May I suggest to update the README with a mention "not production-ready", or "use clementine for now"? That may help those after me.

Good luck and good work were you ever to resume work on this..

**Comment by zachallaun** [comment]
Good suggestion; changed!
